### ISSUE TITLE
V iframu nefunguje tlačítko pro kopírování IRI pojmu

### ISSUE THREAD

**Issue by MichalMed** [opendata-mvcr/showit#129]
Pokud běží ShowIt v iframe, pak neumí zkopírovat IRI pojmu. Navrhovaná řešení:
1. pokud showit může poznat, že je v iframe, pak místo tlačítka zobrazovat iri
1. pokud ne, tak po zmáčknutí tlačítka zobrazit i IRI (někde vedle)

**Comment by londoss** [comment]
> 

Dobrý den,

pro možnost kopírování z pluginu iFRAME pro DokuWiki tato možnost nepomohla. I tak si myslím, že přidat funkčnost na zobrazení URI a pak jeho zkopírování je i uživatelsky lepší, abych věděl, co se mi to do schránky vlastně kopíruje.

V příloze je kód iFRAME pluginu, který využívám.

Děkuji.
[iframe.txt](https://github.com/opendata-mvcr/showit/files/9000643/iframe.txt)

**Comment by FilipKopecky** [comment]
S tímto pluginem obeznámen nejsem, je možné ověřit že posíláte vlastnost `allow="clipboard-write"` a že se tato vlastnost skutečně propíše do finálního HTML? Pokud plugin zamítá tento atribut propsat do finálního HTML, bude zapotřebí plugin přepsat. 

Pokud nemáte kapacity na přepsání pluginu, či jinou modifikaci, je možné IRI zobrazit v tool-tipu při najetí na kopírovací tlačítko, ze kterého byste si mohl dané IRI ručně zkopírovat. 
Z Vašeho komentáře usuzuji, že byste tuto možnost uvítal, začnu tedy tento požadavek zpracovávat.

**Comment by MichalMed** [comment]
@londoss můžete otestovat na netlify? https://slovník.gov.cz/generický/institut-pro-veřejnou-správu/pojem/agenda

**Comment by londoss** [comment]
> @londoss můžete otestovat na netlify? https://deploy-preview-130--sgov-browser.netlify.app/

Dobrý den, funguje, respektive zobrazuje se pop-up s možností kopírování.
