### ISSUE TITLE
Incorrect legislation vocabulary URL namespace split

### ISSUE THREAD

**Issue by karelklima** [opendata-mvcr/showit#75]
When browsing a term from a legislation vocabulary, this is an example of URL I'm getting in the app:

http://localhost:3000/vocabularies/2020/terms/identifikační-číslo-stavby?namespace=https://slovník.gov.cz/legislativní/sbírka/393/

In other words, the vocabulary name is split in a wrong place. Further brainstorming needed how to handle this. Since we're planning to decouple vocabularies and terms, my suggestion would be: `/pojem/[TERM IRI WITHOUT PREFIX]`, where the prefix is `https://slovník.gov.cz/`. And we don't need to include it in the URL, or perhaps include namespace only if it differs from this default one.

Related to #67 

FYI @psiotwo @MichalMed

**Comment by MichalMed** [comment]
Im not sure how is this solving the problem with decoupling terms and vocabs
